"""
Project ISOBAR — Synthetic Asset Register Generator
===================================================

This module generates synthetic credit asset portfolios for testing and validating
the ISOBAR Inverse Risk-Weighted Asset (RWA) Portfolio Shaping Engine.

Domain & Financial Rationale
----------------------------
1. Regulatory Framework:
   Credit risk capital calculations follow the Basel II/III Internal Ratings-Based (IRB)
   Advanced Approach using the Asymptotic Single Risk Factor (ASRF) / Vasicek model.
   Under IRB, regulatory capital requirement K is a non-linear function of:
     - Probability of Default (PD)
     - Loss Given Default (LGD)
     - Effective Maturity (M)
     - Asset Class (Corporate, SME, Retail-Mortgage)

   The Risk Weight (RW) is K * 12.5, converting capital fraction into RWA multiplier:
     RWA_i = EAD_i * RW_i

2. Decoupled Architecture & Precalculated Risk Weights:
   To enable rapid optimization in both classical solvers (e.g. SLSQP) and quantum samplers
   (Simulated Annealing / D-Wave QUBO), each asset bucket pre-calculates its IRB Risk Weight
   (`precalc_rw`) at data generation time. Solvers evaluate linear RWA contributions without
   re-evaluating heavy Gaussian CDFs/quantiles inside optimization inner loops.

3. Credit Rating Grade Calibration & Intra-Grade Heterogeneity:
   Rating grades (AAA through CCC) represent standardized credit risk bands with base PD
   midpoints defined by Basel calibration benchmarks. Within each asset class's eligible
   rating grades, bucket PDs are generated by adding small stochastic noise to the grade's
   base PD and clamping to the asset class's allowed `pd_range`.

4. Origination Limits & Search Space Definition:
   Each asset bucket is assigned a baseline Exposure at Default (`ead_baseline`).
   Policy bounds define origination floors and ceilings:
     - ead_min_limit = ead_baseline * ead_min_factor (policy floor, e.g. 50% of baseline)
     - ead_max_limit = ead_baseline * ead_max_factor (policy ceiling, e.g. 200% of baseline)

   These limits construct bounded decision intervals X_i in [ead_min_limit_i, ead_max_limit_i]
   for classical and quantum portfolio shaping algorithms.
"""

from __future__ import annotations

import os
import sys
import uuid
from pathlib import Path
from typing import Any, Dict, List

import numpy as np
import pandas as pd

# Add /app to sys.path at the top per specification
sys.path.insert(0, '/app')

# Also include workspace root in sys.path for local non-container execution
_PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

from shared.config_loader import IsobarConfig, load_config
from shared.irb import irb_risk_weight
from shared.schemas import AssetRecord


def resolve_config_path() -> Path:
    """
    Locate the ISOBAR configuration YAML file across container and host environments.

    Returns
    -------
    Path
        Absolute path to ``config.yaml``.
    """
    env_path = os.environ.get("ISOBAR_CONFIG")
    if env_path and Path(env_path).exists():
        return Path(env_path)

    container_path = Path("/app/config.yaml")
    if container_path.exists():
        return container_path

    local_path = _PROJECT_ROOT / "config.yaml"
    if local_path.exists():
        return local_path

    raise FileNotFoundError(
        "Configuration file 'config.yaml' not found in /app/config.yaml or workspace root."
    )


def allocate_asset_counts(n_assets: int, asset_classes: List[Any]) -> List[int]:
    """
    Allocate N asset buckets across asset classes using exact quota distribution.

    Uses the Hamilton / Largest Remainder method to ensure integer bucket counts
    sum exactly to N while honoring configured class target weights.

    Parameters
    ----------
    n_assets : int
        Total number of asset buckets to generate.
    asset_classes : List[AssetClassConfig]
        List of asset class configuration objects containing target weights.

    Returns
    -------
    List[int]
        Number of buckets allocated to each asset class.
    """
    weights = np.array([ac.weight for ac in asset_classes], dtype=float)
    weights /= weights.sum()

    exact_counts = n_assets * weights
    counts = np.floor(exact_counts).astype(int)
    remainder = n_assets - int(counts.sum())

    if remainder > 0:
        remainders = exact_counts - counts
        top_indices = np.argsort(remainders)[::-1][:remainder]
        counts[top_indices] += 1

    return counts.tolist()


def generate_synthetic_portfolio(config: IsobarConfig) -> pd.DataFrame:
    """
    Generate synthetic asset register DataFrame conforming to AssetRecord schema.

    Parameters
    ----------
    config : IsobarConfig
        Parsed configuration containing portfolio parameters, seed, and asset class specs.

    Returns
    -------
    pd.DataFrame
        DataFrame containing N asset records with credit risk parameters and precalculated RW.
    """
    seed = config.portfolio.seed
    rng = np.random.default_rng(seed)

    n_assets = config.portfolio.n_assets
    asset_classes = config.portfolio.asset_classes
    rating_pd_map = config.portfolio.rating_pd_map

    mat_min, mat_max = config.portfolio.maturity_range
    ead_min_cfg, ead_max_cfg = config.portfolio.ead_baseline_range
    ead_min_factor = config.portfolio.ead_min_factor
    ead_max_factor = config.portfolio.ead_max_factor

    counts = allocate_asset_counts(n_assets, asset_classes)

    records: List[Dict[str, Any]] = []

    for ac, count in zip(asset_classes, counts):
        ac_name = ac.name
        pd_min, pd_max = ac.pd_range
        lgd_min, lgd_max = ac.lgd_range
        eligible_grades = ac.eligible_grades

        for i in range(count):
            asset_id = str(uuid.uuid4())

            # Cycle through eligible rating grades for balanced credit quality representation
            rating_grade = eligible_grades[i % len(eligible_grades)]
            base_pd = rating_pd_map[rating_grade]

            # Add small relative intra-grade noise (±10% of base_pd) and clamp to class pd_range
            noise = rng.uniform(-0.10 * base_pd, 0.10 * base_pd)
            pd_val = float(np.clip(base_pd + noise, pd_min, pd_max))

            # Sample Loss Given Default (LGD) uniformly within class range
            lgd_val = float(rng.uniform(lgd_min, lgd_max))

            # Sample baseline Exposure at Default (EAD) uniformly within portfolio range
            ead_baseline = float(rng.uniform(ead_min_cfg, ead_max_cfg))

            # Calculate policy origination limits (floor and ceiling)
            ead_min_limit = float(ead_baseline * ead_min_factor)
            ead_max_limit = float(ead_baseline * ead_max_factor)

            # Sample effective maturity in years uniformly within portfolio range
            maturity_years = float(rng.uniform(mat_min, mat_max))

            # Compute Basel Advanced IRB Risk Weight percentage multiplier
            precalc_rw = float(irb_risk_weight(
                pd=pd_val,
                lgd=lgd_val,
                maturity=maturity_years,
                asset_class=ac_name
            ))

            record_dict = {
                "asset_id": asset_id,
                "asset_class": ac_name,
                "rating_grade": rating_grade,
                "pd": pd_val,
                "lgd": lgd_val,
                "ead_baseline": ead_baseline,
                "ead_min_limit": ead_min_limit,
                "ead_max_limit": ead_max_limit,
                "maturity_years": maturity_years,
                "precalc_rw": precalc_rw,
            }

            # Validate against Pydantic AssetRecord schema
            AssetRecord(**record_dict)
            records.append(record_dict)

    df = pd.DataFrame(records)
    return df


def save_portfolio(df: pd.DataFrame, config: IsobarConfig) -> Dict[str, Path]:
    """
    Write asset register DataFrame to disk in CSV format and optionally Parquet format.

    Parameters
    ----------
    df : pd.DataFrame
        Asset register DataFrame.
    config : IsobarConfig
        Configuration object containing output directory and format specs.

    Returns
    -------
    Dict[str, Path]
        Dictionary mapping file format names to saved file paths.
    """
    data_dir = Path(config.output.data_dir)
    os.makedirs(data_dir, exist_ok=True)

    saved_paths: Dict[str, Path] = {}

    # Primary CSV export
    csv_path = data_dir / "asset_register.csv"
    df.to_csv(csv_path, index=False)
    saved_paths["csv"] = csv_path

    # Secondary Parquet export if configured
    if config.output.format.lower() == "parquet":
        try:
            parquet_path = data_dir / "asset_register.parquet"
            df.to_parquet(parquet_path, index=False)
            saved_paths["parquet"] = parquet_path
        except ImportError:
            print("Warning: pyarrow/fastparquet not installed. Parquet export skipped.")

    # Guarantee fallback copy in workspace root data/assets directory when running outside container
    fallback_dir = _PROJECT_ROOT / "data" / "assets"
    if fallback_dir.resolve() != data_dir.resolve():
        os.makedirs(fallback_dir, exist_ok=True)
        df.to_csv(fallback_dir / "asset_register.csv", index=False)
        if config.output.format.lower() == "parquet":
            try:
                df.to_parquet(fallback_dir / "asset_register.parquet", index=False)
            except ImportError:
                pass

    return saved_paths


def print_summary(df: pd.DataFrame) -> None:
    """
    Print portfolio generation summary statistics to stdout.

    Parameters
    ----------
    df : pd.DataFrame
        Generated asset register DataFrame.
    """
    num_assets = len(df)
    total_baseline_ead = float(df["ead_baseline"].sum())
    total_baseline_rwa = float((df["ead_baseline"] * df["precalc_rw"]).sum())
    avg_rw = (total_baseline_rwa / total_baseline_ead) * 100.0 if total_baseline_ead > 0 else 0.0

    print("=" * 80)
    print("Project ISOBAR — Synthetic Asset Register Summary")
    print("=" * 80)
    print(f"Total Asset Buckets Generated : {num_assets}")
    print(f"Total Baseline EAD            : £{total_baseline_ead:,.2f}")
    print(f"Total Baseline RWA            : £{total_baseline_rwa:,.2f}")
    print(f"Portfolio Average Risk Weight : {avg_rw:.2f}%")
    print("-" * 80)
    print("Asset Class Breakdown:")
    for ac_name, group in df.groupby("asset_class"):
        ac_ead = group["ead_baseline"].sum()
        ac_rwa = (group["ead_baseline"] * group["precalc_rw"]).sum()
        ac_share = (ac_ead / total_baseline_ead) * 100.0 if total_baseline_ead > 0 else 0.0
        print(
            f"  - {ac_name:<16}: {len(group):2d} buckets | "
            f"EAD: £{ac_ead:14,.2f} ({ac_share:5.1f}%) | "
            f"RWA: £{ac_rwa:14,.2f}"
        )
    print("=" * 80)


def main() -> None:
    """
    Main entry point for datagen service. Loads configuration, generates
    synthetic portfolio, writes output files, and prints summary.
    """
    config_path = resolve_config_path()
    config = load_config(config_path)

    df = generate_synthetic_portfolio(config)
    saved_paths = save_portfolio(df, config)
    print_summary(df)

    csv_path = saved_paths.get("csv")
    if csv_path:
        print(f"\nAsset register successfully written to: {csv_path}")


if __name__ == "__main__":
    main()
